Hyperion
DroidsOnRoids/Toast-App pull request #162
Opened 2019-02-02 23:07 UTC by tadychdorota

Add Hyperion debug menu with Chuck and AppInfo plugins

2019-02-03 00:33 UTC, koral-- reviewed
Jest więcej rzeczy do poprawienia w związku z podbiciem wersji bibliotek. Zobacz build log na bitrise.

2019-02-03 00:33 UTC, koral-- commented on build.gradle
> +                buildTools: "27.1.1",
Skoro build toolsy zostały wyrzucone z build.gradle, to tu też nie ma sensu tego trzymać.

2019-02-03 00:33 UTC, koral-- commented on app/build.gradle
> +    releaseImplementation 'com.willowtreeapps.hyperion:hyperion-core-no-op:0.9.27'
Po co ten no-op? Nie widać żadnych importów z niego.

2019-02-03 16:13 UTC, mszydlow requested changes

2019-02-03 16:13 UTC, mszydlow commented on app/src/main/java/pl/droidsonroids/toast/viewmodels/contact/ContactViewModel.kt
> +            name -> nameInputError.set(contactFormValidator.getNameError(property.get()!!))
Czy takie zmiany po samym update libek są konieczne?? Dodawanie wszędzie operatora "!!" wydaje mi się niebezpieczne 🤔

2019-02-03 16:47 UTC, koral-- commented on app/src/main/java/pl/droidsonroids/toast/app/photos/PhotosActivity.kt
> +                .apply { photosContainer.rotation = this!!.get()!! }
`this!!` wygląda na zbędne w większości przypadków.

2019-02-03 16:50 UTC, koral-- commented on app/src/main/java/pl/droidsonroids/toast/viewmodels/contact/ContactViewModel.kt
> +            name -> nameInputError.set(contactFormValidator.getNameError(property.get()!!))
`!!` uchodzi raczej za za złą praktykę, ale czasami może być akceptowalne.
W takich przypadkach jak ten powinien istnieć jakiś extension w stylu `requireValue()` który wyrzuca wyjątek z sensownym messagem jeśli wartość będzie nullem.

2019-02-03 16:52 UTC, koral-- commented on build.gradle
> +                kotlin    : "1.3.11",
Jeśli podbijać wersje to zwykle do najnowszych stabilnych (chyba, że jest jakiś dodatkowy breaking change czasochłonny). W tym przypadku można podbić do 1.3.20

2019-02-03 16:53 UTC, koral-- commented on build.gradle
> +        classpath 'io.fabric.tools:gradle:1.27.0'
ZTCP najnowsza stabilna wersja to 1.27.1

2019-02-03 16:54 UTC, koral-- commented on app/src/main/res/values/strings.xml
> +    <string name="hbc_target_build_config_name">pl.droidsonroids.toast.BuildConfig</string>
To raczej nie powinno być w main tylko w sourcesetach gdzie Hyperion jest faktycznie używany. `debug` w przypadku tego projektu.

2019-02-03 17:47 UTC, koral-- commented on app/proguard-rules.pro
> +-keep class com.willowtreeapps.hyperion.sample.BuildConfig { *; }
Tu powinna być właściwa nazwa pakietu. `com.willowtreeapps.hyperion.sample` to tylko przykładowa wartość z readme.

2019-02-03 18:01 UTC, koral-- commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
Przy podbijaniu wersji Gradle warto puścić task `wrapper`, żeby wygenerował się nowy wrapper. https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

2019-02-12 07:51 UTC, tadychdorota commented on build.gradle
> +                buildTools: "27.1.1",
Usunięte

2019-02-12 07:52 UTC, tadychdorota commented on app/proguard-rules.pro
> +-keep class com.willowtreeapps.hyperion.sample.BuildConfig { *; }
Racja, zapomniałam podmienić. Już powinno być dobrze.

2019-03-05 08:58 UTC, tadychdorota commented on app/build.gradle
> +    releaseImplementation 'com.willowtreeapps.hyperion:hyperion-core-no-op:0.9.27'
racja, usuwam

2019-03-05 10:59 UTC, koral-- commented on app/build.gradle
> +         //   minifyEnabled true
Celowa ta zmiana?

2020-11-17 14:13 UTC, closed without merging